// Code generated by hertz generator.

package user

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _updateprofileMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _getuserbyidMw() []app.HandlerFunc {
	// 公开接口，不需要认证
	return nil
}

func _switchcurrentteamMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}

}
