// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"orbia_api/biz/mw"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _updateprofileMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getuserbyidMw() []app.HandlerFunc {
	// 公开接口，不需要认证
	return nil
}
