// Code generated by hertz generator.

package order

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// 所有订单接口都需要认证，普通用户和管理员都可访问
	return []app.HandlerFunc{
		mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin),
	}
}

func _cancelorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _kolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getkolordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
