// Code generated by hertz generator.

package recharge_order

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// admin路由需要管理员权限
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleAdmin)}
}

func _rechargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

// admin确认充值订单 - 仅管理员
func _confirmrechargeorderMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleAdmin)}
}

// admin查询所有充值订单 - 仅管理员
func _getallrechargeordersMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleAdmin)}
}

// admin拒绝充值订单 - 仅管理员
func _rejectrechargeorderMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleAdmin)}
}

func _recharge0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 创建加密货币充值订单 - 普通用户和管理员都可以
func _createcryptorechargeorderMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

// 创建在线支付充值订单 - 普通用户和管理员都可以
func _createonlinerechargeorderMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 查询充值订单详情 - 普通用户和管理员都可以
func _getrechargeorderdetailMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _myMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 查询我的充值订单列表 - 普通用户和管理员都可以
func _getmyrechargeordersMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}
