// Code generated by hertz generator.

package kol

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _kolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applykolMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _getkolinfoMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _getkollistMw() []app.HandlerFunc {
	// 需要JWT认证
	return nil
}

func _getkolplansMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _reviewkolMw() []app.HandlerFunc {
	// 需要JWT认证，且仅管理员可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleAdmin)}
}

func _updatekolinfoMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _getkolvideosMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _planMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletekolplanMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _savekolplanMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _statsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatekolstatsMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createkolvideoMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _deletekolvideoMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}

func _updatekolvideoMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleUser, consts.RoleAdmin)}
}
