// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "orbia_api/biz/model/order/user"
)

// GetProfile .
// @router /api/v1/user/profile [POST]
func GetProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.GetProfileResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateProfile .
// @router /api/v1/user/update-profile [POST]
func UpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UpdateProfileResp)

	c.JSON(consts.StatusOK, resp)
}

// SwitchCurrentTeam .
// @router /api/v1/user/switch-team [POST]
func SwitchCurrentTeam(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SwitchCurrentTeamReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.SwitchCurrentTeamResp)

	c.JSON(consts.StatusOK, resp)
}

// GetUserById .
// @router /api/v1/user/:user_id [POST]
func GetUserById(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserByIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.GetUserByIdResp)

	c.JSON(consts.StatusOK, resp)
}
