# Orbia API 配置文件

# 服务配置
server:
  host: 0.0.0.0
  port: 8888
  read_timeout: 30s
  write_timeout: 30s

# 数据库配置
database:
  mysql:
    host: 127.0.0.1
    port: 3306
    database: orbia
    username: root
    password: root123
    charset: utf8mb4
    parse_time: true
    loc: Local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600

# Redis 配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT 配置
jwt:
  secret: orbia_secret_key_change_in_production
  expire_hours: 24

# 日志配置
log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 7
  max_age: 30

# Cloudflare R2 配置
r2:
  endpoint: "https://5133106b5806397669e2897825b57d81.r2.cloudflarestorage.com"
  access_key: "e37979d3a17e64041ffd833beee6d90c"
  secret_key: "4fedacceaef6285a0330d586142c15ace48280acbcd7a6f1400c92271a2e2d37"
  bucket: "orbia"
  public_url: "https://pub-7fecd33efbfc4271b901992eefd6a9ba.r2.dev"
  upload_token_expire_minutes: 30  # 上传token过期时间（分钟）
  max_file_size: 10485760          # 默认最大文件大小（10MB）
  
  # 按文件扩展名配置
  allowed_extensions:
    # 图片类型
    .jpg:
      max_size: 10485760  # 10MB
      default_path: "images"
    .jpeg:
      max_size: 10485760  # 10MB
      default_path: "images"
    .png:
      max_size: 10485760  # 10MB
      default_path: "images"
    .gif:
      max_size: 5242880   # 5MB
      default_path: "images"
    .webp:
      max_size: 10485760  # 10MB
      default_path: "images"
    
    # 文档类型
    .pdf:
      max_size: 52428800  # 50MB
      default_path: "documents"
    .doc:
      max_size: 20971520  # 20MB
      default_path: "documents"
    .docx:
      max_size: 20971520  # 20MB
      default_path: "documents"
    .xls:
      max_size: 20971520  # 20MB
      default_path: "documents"
    .xlsx:
      max_size: 20971520  # 20MB
      default_path: "documents"
    .ppt:
      max_size: 52428800  # 50MB
      default_path: "documents"
    .pptx:
      max_size: 52428800  # 50MB
      default_path: "documents"
    .txt:
      max_size: 1048576   # 1MB
      default_path: "documents"
    
    # 视频类型
    .mp4:
      max_size: 104857600  # 100MB
      default_path: "videos"
    .mov:
      max_size: 104857600  # 100MB
      default_path: "videos"
    .avi:
      max_size: 104857600  # 100MB
      default_path: "videos"

# SMTP 邮件配置
smtp:
  server: "mail.smtp2go.com"
  port: "2525"  # 使用2525端口（587端口被阻塞）
  username: "ngd.neo.org"
  password: "3ukd6UhQ0mF8pUlS"
  email: "verification@cypherai.network"
  from_name: "Orbia App"

# 验证码配置
verification_code:
  expire_minutes: 10  # 验证码过期时间（分钟）
  length: 6           # 验证码长度

