# Orbia API 配置文件

# 服务配置
server:
  host: 0.0.0.0
  port: 8888
  read_timeout: 30s
  write_timeout: 30s

# 数据库配置
database:
  mysql:
    host: 127.0.0.1
    port: 3306
    database: orbia
    username: root
    password: root123
    charset: utf8mb4
    parse_time: true
    loc: Local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600

# Redis 配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT 配置
jwt:
  secret: orbia_secret_key_change_in_production
  expire_hours: 24

# 日志配置
log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 7
  max_age: 30

# Cloudflare R2 配置
r2:
  endpoint: "https://5133106b5806397669e2897825b57d81.r2.cloudflarestorage.com"
  access_key: "e37979d3a17e64041ffd833beee6d90c"
  secret_key: "4fedacceaef6285a0330d586142c15ace48280acbcd7a6f1400c92271a2e2d37"
  bucket: "orbia"
  public_url: "https://pub-7fecd33efbfc4271b901992eefd6a9ba.r2.dev"
  upload_token_expire_minutes: 30  # 上传token过期时间（分钟）
  max_file_size: 10485760          # 最大文件大小（10MB）

