// Code generated by hertz generator.

package dictionary

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _v1Mw() []app.HandlerFunc {
	return nil
}

func _adminMw() []app.HandlerFunc {
	// 所有admin路由都需要admin权限
	return []app.HandlerFunc{
		mw.AuthMiddleware(consts.RoleAdmin),
	}
}

func _dictionaryMw() []app.HandlerFunc {
	return nil
}

func _getdictionarybycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdictionariesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _itemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionaryitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedictionaryitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdictionaryitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionaryitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictionary0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdictionarytreeMw() []app.HandlerFunc {
	// your code...
	return nil
}
