// Code generated by hertz generator.

package upload

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generateuploadtokenMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin),
	}
}

func _validateimageurlMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{
		mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin),
	}
}

func _validatefileurlMw() []app.HandlerFunc {
	// your code...
	return nil
}
