// Code generated by hertz generator.

package user

import (
	"context"
	"net/http"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"orbia_api/biz/dal/mysql"
	"orbia_api/biz/model/common"
	"orbia_api/biz/model/kol"
	"orbia_api/biz/model/team"
	user "orbia_api/biz/model/user"
	"orbia_api/biz/mw"
	userService "orbia_api/biz/service/user"
)

var (
	userSvc userService.UserService
)

// InitUserService 初始化用户服务
func InitUserService() {
	userRepo := mysql.NewUserRepository(mysql.DB)
	teamRepo := mysql.NewTeamRepository(mysql.DB)
	kolRepo := mysql.NewKolRepository(mysql.DB)
	userSvc = userService.NewUserService(userRepo, teamRepo, kolRepo)
}

// GetProfile 获取用户资料
// @router /api/v1/user/profile [POST]
func GetProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.Errorf("GetProfile bind error: %v", err)
		c.JSON(http.StatusBadRequest, &user.GetProfileResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: "Invalid request parameters: " + err.Error(),
			},
		})
		return
	}

	// 从JWT中间件获取用户ID
	userID, exists := mw.GetAuthUserID(c)
	if !exists {
		hlog.Error("GetProfile: user ID not found in context")
		c.JSON(http.StatusUnauthorized, &user.GetProfileResp{
			BaseResp: &common.BaseResp{
				Code:    401,
				Message: "User not authenticated",
			},
		})
		return
	}

	// 调用服务层获取用户信息
	userInfo, currentTeam, kolInfo, err := userSvc.GetProfile(userID)
	if err != nil {
		hlog.Errorf("GetProfile service error: %v", err)
		c.JSON(http.StatusNotFound, &user.GetProfileResp{
			BaseResp: &common.BaseResp{
				Code:    404,
				Message: err.Error(),
			},
		})
		return
	}

	// 转换为响应格式
	userResp := &user.UserInfo{
		ID:            userInfo.ID,
		WalletAddress: userInfo.WalletAddress,
		Email:         userInfo.Email,
		Nickname:      userInfo.Nickname,
		AvatarURL:     userInfo.AvatarURL,
		Role:          userInfo.Role,
		KolID:         userInfo.KolID,
		CreatedAt:     userInfo.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:     userInfo.UpdatedAt.Format("2006-01-02 15:04:05"),
	}

	// 如果有当前团队信息，添加到响应中
	if currentTeam != nil {
		userResp.CurrentTeam = &team.Team{
			ID:        currentTeam.ID,
			Name:      currentTeam.Name,
			IconURL:   currentTeam.IconURL,
			CreatorID: currentTeam.CreatorID,
			CreatedAt: currentTeam.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt: currentTeam.UpdatedAt.Format("2006-01-02 15:04:05"),
		}
	}

	// 如果有KOL信息，添加到响应中
	if kolInfo != nil && kolInfo.Kol != nil {
		userResp.KolInfo = convertKolInfo(kolInfo)
	}

	resp := &user.GetProfileResp{
		User: userResp,
		BaseResp: &common.BaseResp{
			Code:    200,
			Message: "Success",
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateProfile 更新用户资料
// @router /api/v1/user/update-profile [POST]
func UpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.Errorf("UpdateProfile bind error: %v", err)
		c.JSON(http.StatusBadRequest, &user.UpdateProfileResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: "Invalid request parameters: " + err.Error(),
			},
		})
		return
	}

	// 从JWT中间件获取用户ID
	userID, exists := mw.GetAuthUserID(c)
	if !exists {
		hlog.Error("UpdateProfile: user ID not found in context")
		c.JSON(http.StatusUnauthorized, &user.UpdateProfileResp{
			BaseResp: &common.BaseResp{
				Code:    401,
				Message: "User not authenticated",
			},
		})
		return
	}

	// 调用服务层更新用户信息
	err = userSvc.UpdateProfile(userID, req.Nickname, req.AvatarURL)
	if err != nil {
		hlog.Errorf("UpdateProfile service error: %v", err)
		c.JSON(http.StatusBadRequest, &user.UpdateProfileResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: err.Error(),
			},
		})
		return
	}

	resp := &user.UpdateProfileResp{
		BaseResp: &common.BaseResp{
			Code:    200,
			Message: "Profile updated successfully",
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetUserById 根据ID获取用户信息
// @router /api/v1/user/:user_id [POST]
func GetUserById(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserByIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.Errorf("GetUserById bind error: %v", err)
		c.JSON(http.StatusBadRequest, &user.GetUserByIdResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: "Invalid request parameters: " + err.Error(),
			},
		})
		return
	}

	// 从路径参数获取用户ID
	userIDStr := c.Param("user_id")
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		hlog.Errorf("GetUserById parse user_id error: %v", err)
		c.JSON(http.StatusBadRequest, &user.GetUserByIdResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: "Invalid user ID format",
			},
		})
		return
	}

	// 调用服务层获取用户信息
	userInfo, err := userSvc.GetUserByID(userID)
	if err != nil {
		hlog.Errorf("GetUserById service error: %v", err)
		c.JSON(http.StatusNotFound, &user.GetUserByIdResp{
			BaseResp: &common.BaseResp{
				Code:    404,
				Message: err.Error(),
			},
		})
		return
	}

	// 转换为响应格式
	userResp := &user.UserInfo{
		ID:            userInfo.ID,
		WalletAddress: userInfo.WalletAddress,
		Email:         userInfo.Email,
		Nickname:      userInfo.Nickname,
		AvatarURL:     userInfo.AvatarURL,
		Role:          userInfo.Role,
		KolID:         userInfo.KolID,
		CreatedAt:     userInfo.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:     userInfo.UpdatedAt.Format("2006-01-02 15:04:05"),
	}

	resp := &user.GetUserByIdResp{
		User: userResp,
		BaseResp: &common.BaseResp{
			Code:    200,
			Message: "Success",
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// SwitchCurrentTeam .
// @router /api/v1/user/switch-team [POST]
func SwitchCurrentTeam(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SwitchCurrentTeamReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 获取用户ID
	userID, exists := mw.GetAuthUserID(c)
	if !exists {
		c.JSON(http.StatusUnauthorized, &user.SwitchCurrentTeamResp{
			BaseResp: &common.BaseResp{
				Code:    401,
				Message: "User not authenticated",
			},
		})
		return
	}

	// 调用服务层切换团队
	switchedTeam, err := userSvc.SwitchCurrentTeam(userID, req.TeamID)
	if err != nil {
		hlog.Errorf("SwitchCurrentTeam service error: %v", err)
		c.JSON(http.StatusBadRequest, &user.SwitchCurrentTeamResp{
			BaseResp: &common.BaseResp{
				Code:    400,
				Message: err.Error(),
			},
		})
		return
	}

	resp := &user.SwitchCurrentTeamResp{
		BaseResp: &common.BaseResp{
			Code:    200,
			Message: "Team switched successfully",
		},
		CurrentTeam: &team.Team{
			ID:        switchedTeam.ID,
			Name:      switchedTeam.Name,
			IconURL:   switchedTeam.IconURL,
			CreatorID: switchedTeam.CreatorID,
			CreatedAt: switchedTeam.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt: switchedTeam.UpdatedAt.Format("2006-01-02 15:04:05"),
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// convertKolInfo 将 KOL 信息转换为响应格式
func convertKolInfo(kolInfo *userService.KolInfo) *kol.KolInfo {
	if kolInfo == nil || kolInfo.Kol == nil {
		return nil
	}

	// 辅助函数：将指针字符串转换为字符串
	ptrToStr := func(s *string) string {
		if s != nil {
			return *s
		}
		return ""
	}

	kolResp := &kol.KolInfo{
		ID:           kolInfo.Kol.ID,
		UserID:       kolInfo.Kol.UserID,
		AvatarURL:    ptrToStr(kolInfo.Kol.AvatarURL),
		DisplayName:  ptrToStr(kolInfo.Kol.DisplayName),
		Description:  ptrToStr(kolInfo.Kol.Description),
		Country:      ptrToStr(kolInfo.Kol.Country),
		TiktokURL:    ptrToStr(kolInfo.Kol.TiktokURL),
		YoutubeURL:   ptrToStr(kolInfo.Kol.YoutubeURL),
		XURL:         ptrToStr(kolInfo.Kol.XURL),
		DiscordURL:   ptrToStr(kolInfo.Kol.DiscordURL),
		Status:       kolInfo.Kol.Status,
		RejectReason: ptrToStr(kolInfo.Kol.RejectReason),
		CreatedAt:    kolInfo.Kol.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:    kolInfo.Kol.UpdatedAt.Format("2006-01-02 15:04:05"),
	}

	if kolInfo.Kol.ApprovedAt != nil {
		approvedAt := kolInfo.Kol.ApprovedAt.Format("2006-01-02 15:04:05")
		kolResp.ApprovedAt = approvedAt
	}

	// 添加语言列表
	kolResp.Languages = make([]*kol.KolLanguage, 0, len(kolInfo.Languages))
	for _, lang := range kolInfo.Languages {
		kolResp.Languages = append(kolResp.Languages, &kol.KolLanguage{
			LanguageCode: lang.LanguageCode,
			LanguageName: lang.LanguageName,
		})
	}

	// 添加标签列表
	kolResp.Tags = make([]*kol.KolTag, 0, len(kolInfo.Tags))
	for _, tag := range kolInfo.Tags {
		kolResp.Tags = append(kolResp.Tags, &kol.KolTag{
			Tag: tag.Tag,
		})
	}

	// 添加统计数据
	if kolInfo.Stats != nil {
		kolResp.Stats = &kol.KolStats{
			TotalFollowers:     kolInfo.Stats.TotalFollowers,
			TiktokFollowers:    kolInfo.Stats.TiktokFollowers,
			YoutubeSubscribers: kolInfo.Stats.YoutubeSubscribers,
			XFollowers:         kolInfo.Stats.XFollowers,
			DiscordMembers:     kolInfo.Stats.DiscordMembers,
			TiktokAvgViews:     kolInfo.Stats.TiktokAvgViews,
			EngagementRate:     kolInfo.Stats.EngagementRate,
		}
	} else {
		// 返回默认的统计数据
		kolResp.Stats = &kol.KolStats{
			TotalFollowers:     0,
			TiktokFollowers:    0,
			YoutubeSubscribers: 0,
			XFollowers:         0,
			DiscordMembers:     0,
			TiktokAvgViews:     0,
			EngagementRate:     0,
		}
	}

	return kolResp
}
