// Code generated by hertz generator.

package conversation

import (
	"orbia_api/biz/consts"
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _getconversationsMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _getmessagesMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _markmessagesreadMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _sendmessageMw() []app.HandlerFunc {
	// 需要JWT认证，普通用户和管理员都可访问
	return []app.HandlerFunc{mw.AuthMiddleware(consts.RoleNormal, consts.RoleAdmin)}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}
