// Code generated by hertz generator.

package wallet

import (
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _walletMw() []app.HandlerFunc {
	// 钱包相关接口需要身份验证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getwalletinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettransactionlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rechargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cryptoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cryptorechargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmcryptorechargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _onlinerechargeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettransactiondetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
