// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaKolPlan = "orbia_kol_plan"

// OrbiaKolPlan KOL报价Plans表
type OrbiaKolPlan struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:Plan ID" json:"id"`                                                     // Plan ID
	KolID       int64          `gorm:"column:kol_id;type:bigint;not null;comment:KOL ID" json:"kol_id"`                                                                   // KOL ID
	Title       string         `gorm:"column:title;type:varchar(200);not null;comment:报价标题" json:"title"`                                                                 // 报价标题
	Description *string        `gorm:"column:description;type:text;comment:报价描述" json:"description"`                                                                      // 报价描述
	Price       float64        `gorm:"column:price;type:decimal(10,2);not null;comment:价格（美元）" json:"price"`                                                              // 价格（美元）
	PlanType    string         `gorm:"column:plan_type;type:enum('basic','standard','premium');not null;comment:Plan类型：basic-基础，standard-标准，premium-高级" json:"plan_type"` // Plan类型：basic-基础，standard-标准，premium-高级
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                         // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                                  // 软删除时间
}

// TableName OrbiaKolPlan's table name
func (*OrbiaKolPlan) TableName() string {
	return TableNameOrbiaKolPlan
}
