// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrbiaKolTag = "orbia_kol_tag"

// OrbiaKolTag KOL标签表
type OrbiaKolTag struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`                  // ID
	KolID     int64      `gorm:"column:kol_id;type:bigint;not null;comment:KOL ID" json:"kol_id"`                           // KOL ID
	Tag       string     `gorm:"column:tag;type:varchar(50);not null;comment:标签，如：Defi, Web3, NFT" json:"tag"`              // 标签，如：Defi, Web3, NFT
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName OrbiaKolTag's table name
func (*OrbiaKolTag) TableName() string {
	return TableNameOrbiaKolTag
}
