// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaKol = "orbia_kol"

// OrbiaKol KOL信息表
type OrbiaKol struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:KOL ID" json:"id"`                                                                       // KOL ID
	UserID       int64          `gorm:"column:user_id;type:bigint;not null;comment:关联用户ID" json:"user_id"`                                                                                  // 关联用户ID
	AvatarURL    *string        `gorm:"column:avatar_url;type:varchar(500);comment:KOL头像URL" json:"avatar_url"`                                                                             // KOL头像URL
	DisplayName  *string        `gorm:"column:display_name;type:varchar(100);comment:KOL显示名称" json:"display_name"`                                                                          // KOL显示名称
	Description  *string        `gorm:"column:description;type:text;comment:KOL描述" json:"description"`                                                                                      // KOL描述
	Country      *string        `gorm:"column:country;type:varchar(50);comment:所在国家" json:"country"`                                                                                        // 所在国家
	TiktokURL    *string        `gorm:"column:tiktok_url;type:varchar(500);comment:TikTok地址" json:"tiktok_url"`                                                                             // TikTok地址
	YoutubeURL   *string        `gorm:"column:youtube_url;type:varchar(500);comment:Youtube地址" json:"youtube_url"`                                                                          // Youtube地址
	XURL         *string        `gorm:"column:x_url;type:varchar(500);comment:X(Twitter)地址" json:"x_url"`                                                                                   // X(Twitter)地址
	DiscordURL   *string        `gorm:"column:discord_url;type:varchar(500);comment:Discord地址" json:"discord_url"`                                                                          // Discord地址
	Status       string         `gorm:"column:status;type:enum('pending','approved','rejected');not null;default:pending;comment:审核状态：pending-待审核，approved-已通过，rejected-已拒绝" json:"status"` // 审核状态：pending-待审核，approved-已通过，rejected-已拒绝
	RejectReason *string        `gorm:"column:reject_reason;type:text;comment:拒绝原因" json:"reject_reason"`                                                                                   // 拒绝原因
	ApprovedAt   *time.Time     `gorm:"column:approved_at;type:timestamp;comment:审核通过时间" json:"approved_at"`                                                                                // 审核通过时间
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                          // 创建时间
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                          // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                                                   // 软删除时间
}

// TableName OrbiaKol's table name
func (*OrbiaKol) TableName() string {
	return TableNameOrbiaKol
}
