// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrbiaPlatformStat = "orbia_platform_stats"

// OrbiaPlatformStat 平台数据统计表
type OrbiaPlatformStat struct {
	ID                     int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:统计ID（此表只有一行数据）" json:"id"`                                        // 统计ID（此表只有一行数据）
	ActiveKols             int64      `gorm:"column:active_kols;type:bigint;not null;comment:活跃的KOLs数量" json:"active_kols"`                                                // 活跃的KOLs数量
	TotalCoverage          int64      `gorm:"column:total_coverage;type:bigint;not null;comment:总覆盖用户数" json:"total_coverage"`                                             // 总覆盖用户数
	TotalAdImpressions     int64      `gorm:"column:total_ad_impressions;type:bigint;not null;comment:累计广告曝光次数" json:"total_ad_impressions"`                               // 累计广告曝光次数
	TotalTransactionAmount float64    `gorm:"column:total_transaction_amount;type:decimal(15,2);not null;default:0.00;comment:平台总交易额（美元）" json:"total_transaction_amount"` // 平台总交易额（美元）
	AverageRoi             float64    `gorm:"column:average_roi;type:decimal(10,2);not null;default:0.00;comment:平均ROI（百分比，如：15.5表示15.5%）" json:"average_roi"`             // 平均ROI（百分比，如：15.5表示15.5%）
	AverageCpm             float64    `gorm:"column:average_cpm;type:decimal(10,2);not null;default:0.00;comment:平均CPM（Cost Per Mille，每千次展示成本）" json:"average_cpm"`        // 平均CPM（Cost Per Mille，每千次展示成本）
	Web3BrandCount         int64      `gorm:"column:web3_brand_count;type:bigint;not null;comment:合作Web3品牌数" json:"web3_brand_count"`                                      // 合作Web3品牌数
	CreatedAt              *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                   // 创建时间
	UpdatedAt              *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                   // 更新时间
}

// TableName OrbiaPlatformStat's table name
func (*OrbiaPlatformStat) TableName() string {
	return TableNameOrbiaPlatformStat
}
