// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaCampaignAttachment = "orbia_campaign_attachment"

// OrbiaCampaignAttachment Campaign附件表
type OrbiaCampaignAttachment struct {
	ID         int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:附件ID" json:"id"`                // 附件ID
	CampaignID int64          `gorm:"column:campaign_id;type:bigint;not null;comment:关联Campaign ID" json:"campaign_id"`          // 关联Campaign ID
	FileURL    string         `gorm:"column:file_url;type:varchar(1000);not null;comment:文件URL" json:"file_url"`                 // 文件URL
	FileName   string         `gorm:"column:file_name;type:varchar(500);not null;comment:文件名" json:"file_name"`                  // 文件名
	FileType   string         `gorm:"column:file_type;type:varchar(100);not null;comment:文件类型（MIME类型）" json:"file_type"`         // 文件类型（MIME类型）
	FileSize   *int64         `gorm:"column:file_size;type:bigint;comment:文件大小（字节）" json:"file_size"`                            // 文件大小（字节）
	CreatedAt  *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                          // 软删除时间
}

// TableName OrbiaCampaignAttachment's table name
func (*OrbiaCampaignAttachment) TableName() string {
	return TableNameOrbiaCampaignAttachment
}
