// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaExcellentCase = "orbia_excellent_case"

// OrbiaExcellentCase 优秀广告案例表
type OrbiaExcellentCase struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:案例ID" json:"id"`                // 案例ID
	VideoURL    string         `gorm:"column:video_url;type:varchar(1000);not null;comment:视频URL" json:"video_url"`               // 视频URL
	CoverURL    string         `gorm:"column:cover_url;type:varchar(1000);not null;comment:封面URL" json:"cover_url"`               // 封面URL
	Title       string         `gorm:"column:title;type:varchar(200);not null;comment:案例标题" json:"title"`                         // 案例标题
	Description *string        `gorm:"column:description;type:text;comment:案例描述" json:"description"`                              // 案例描述
	SortOrder   int32          `gorm:"column:sort_order;type:int;not null;comment:排序序号（升序，数字越小越靠前）" json:"sort_order"`            // 排序序号（升序，数字越小越靠前）
	Status      int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`          // 状态：1-启用，0-禁用
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                          // 软删除时间
}

// TableName OrbiaExcellentCase's table name
func (*OrbiaExcellentCase) TableName() string {
	return TableNameOrbiaExcellentCase
}
