// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaPaymentSetting = "orbia_payment_setting"

// OrbiaPaymentSetting 收款钱包设置表
type OrbiaPaymentSetting struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:设置ID" json:"id"`                               // 设置ID
	Network   string         `gorm:"column:network;type:varchar(100);not null;comment:区块链网络（如：TRC-20 - TRON Network (TRC-20)）" json:"network"` // 区块链网络（如：TRC-20 - TRON Network (TRC-20)）
	Address   string         `gorm:"column:address;type:varchar(500);not null;comment:钱包地址" json:"address"`                                    // 钱包地址
	Label     string         `gorm:"column:label;type:varchar(200);not null;comment:钱包标签（如：USDT-TRC20 主钱包）" json:"label"`                      // 钱包标签（如：USDT-TRC20 主钱包）
	Status    int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`                         // 状态：1-启用，0-禁用
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                         // 软删除时间
}

// TableName OrbiaPaymentSetting's table name
func (*OrbiaPaymentSetting) TableName() string {
	return TableNameOrbiaPaymentSetting
}
