// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrbiaVerificationCode = "orbia_verification_code"

// OrbiaVerificationCode 验证码表
type OrbiaVerificationCode struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                                                                     // 自增ID
	Email     string     `gorm:"column:email;type:varchar(255);not null;comment:邮箱地址" json:"email"`                                                                                              // 邮箱地址
	Code      string     `gorm:"column:code;type:varchar(10);not null;comment:验证码" json:"code"`                                                                                                  // 验证码
	CodeType  string     `gorm:"column:code_type;type:enum('login','register','reset_password');not null;default:login;comment:验证码类型：login-登录，register-注册，reset_password-重置密码" json:"code_type"` // 验证码类型：login-登录，register-注册，reset_password-重置密码
	Status    string     `gorm:"column:status;type:enum('unused','used','expired');not null;default:unused;comment:状态：unused-未使用，used-已使用，expired-已过期" json:"status"`                            // 状态：unused-未使用，used-已使用，expired-已过期
	UsedAt    *time.Time `gorm:"column:used_at;type:timestamp;comment:使用时间" json:"used_at"`                                                                                                      // 使用时间
	ExpiresAt time.Time  `gorm:"column:expires_at;type:timestamp;not null;comment:过期时间" json:"expires_at"`                                                                                       // 过期时间
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                      // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                      // 更新时间
}

// TableName OrbiaVerificationCode's table name
func (*OrbiaVerificationCode) TableName() string {
	return TableNameOrbiaVerificationCode
}
