// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrbiaKolStat = "orbia_kol_stats"

// OrbiaKolStat KOL数据统计表
type OrbiaKolStat struct {
	ID                 int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                    // ID
	KolID              int64      `gorm:"column:kol_id;type:bigint;not null;comment:KOL ID" json:"kol_id"`                                             // KOL ID
	TotalFollowers     *int64     `gorm:"column:total_followers;type:bigint;comment:全社交网站粉丝总数" json:"total_followers"`                                 // 全社交网站粉丝总数
	TiktokFollowers    *int64     `gorm:"column:tiktok_followers;type:bigint;comment:TikTok粉丝数" json:"tiktok_followers"`                               // TikTok粉丝数
	YoutubeSubscribers *int64     `gorm:"column:youtube_subscribers;type:bigint;comment:Youtube订阅数" json:"youtube_subscribers"`                        // Youtube订阅数
	XFollowers         *int64     `gorm:"column:x_followers;type:bigint;comment:X粉丝数" json:"x_followers"`                                              // X粉丝数
	DiscordMembers     *int64     `gorm:"column:discord_members;type:bigint;comment:Discord成员数" json:"discord_members"`                                // Discord成员数
	TiktokAvgViews     *int64     `gorm:"column:tiktok_avg_views;type:bigint;comment:TikTok视频平均观看数" json:"tiktok_avg_views"`                           // TikTok视频平均观看数
	EngagementRate     *float64   `gorm:"column:engagement_rate;type:decimal(10,2);default:0.00;comment:订阅指数（Engagement Rate）" json:"engagement_rate"` // 订阅指数（Engagement Rate）
	CreatedAt          *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt          *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                   // 更新时间
}

// TableName OrbiaKolStat's table name
func (*OrbiaKolStat) TableName() string {
	return TableNameOrbiaKolStat
}
