// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaKolVideo = "orbia_kol_video"

// OrbiaKolVideo KOL视频表
type OrbiaKolVideo struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:视频ID" json:"id"`                // 视频ID
	KolID           int64          `gorm:"column:kol_id;type:bigint;not null;comment:KOL ID" json:"kol_id"`                           // KOL ID
	Title           string         `gorm:"column:title;type:varchar(500);not null;comment:视频标题" json:"title"`                         // 视频标题
	Content         *string        `gorm:"column:content;type:text;comment:视频内容/描述" json:"content"`                                   // 视频内容/描述
	CoverURL        *string        `gorm:"column:cover_url;type:varchar(500);comment:视频封面URL" json:"cover_url"`                       // 视频封面URL
	VideoURL        *string        `gorm:"column:video_url;type:varchar(500);comment:视频链接" json:"video_url"`                          // 视频链接
	Platform        string         `gorm:"column:platform;type:varchar(50);not null;comment:平台：tiktok, youtube" json:"platform"`      // 平台：tiktok, youtube
	PlatformVideoID *string        `gorm:"column:platform_video_id;type:varchar(200);comment:平台视频ID" json:"platform_video_id"`        // 平台视频ID
	LikesCount      *int64         `gorm:"column:likes_count;type:bigint;comment:点赞数" json:"likes_count"`                             // 点赞数
	ViewsCount      *int64         `gorm:"column:views_count;type:bigint;comment:观看数" json:"views_count"`                             // 观看数
	CommentsCount   *int64         `gorm:"column:comments_count;type:bigint;comment:评论数" json:"comments_count"`                       // 评论数
	SharesCount     *int64         `gorm:"column:shares_count;type:bigint;comment:分享数" json:"shares_count"`                           // 分享数
	PublishedAt     *time.Time     `gorm:"column:published_at;type:timestamp;comment:发布时间" json:"published_at"`                       // 发布时间
	CreatedAt       *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                          // 软删除时间
}

// TableName OrbiaKolVideo's table name
func (*OrbiaKolVideo) TableName() string {
	return TableNameOrbiaKolVideo
}
