// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaContentTrend = "orbia_content_trend"

// OrbiaContentTrend 内容趋势表
type OrbiaContentTrend struct {
	ID         int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:趋势ID" json:"id"`                                         // 趋势ID
	Ranking    int32          `gorm:"column:ranking;type:int;not null;comment:排名（1,2,3,4,5...）" json:"ranking"`                                           // 排名（1,2,3,4,5...）
	HotKeyword string         `gorm:"column:hot_keyword;type:varchar(200);not null;comment:热点词（如：defi, web3等）" json:"hot_keyword"`                        // 热点词（如：defi, web3等）
	ValueLevel string         `gorm:"column:value_level;type:enum('low','medium','high');not null;comment:价值等级：low-低，medium-中，high-高" json:"value_level"` // 价值等级：low-低，medium-中，high-高
	Heat       int64          `gorm:"column:heat;type:bigint;not null;comment:热度值" json:"heat"`                                                           // 热度值
	GrowthRate float64        `gorm:"column:growth_rate;type:decimal(10,2);not null;default:0.00;comment:增长比例（百分比，如：15.5表示15.5%）" json:"growth_rate"`     // 增长比例（百分比，如：15.5表示15.5%）
	Status     int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`                                   // 状态：1-启用，0-禁用
	CreatedAt  *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                          // 创建时间
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                          // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                   // 软删除时间
}

// TableName OrbiaContentTrend's table name
func (*OrbiaContentTrend) TableName() string {
	return TableNameOrbiaContentTrend
}
