// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrbiaDictionaryItem = "orbia_dictionary_item"

// OrbiaDictionaryItem 数据字典项表
type OrbiaDictionaryItem struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:字典项ID" json:"id"`               // 字典项ID
	DictionaryID int64          `gorm:"column:dictionary_id;type:bigint;not null;comment:字典ID" json:"dictionary_id"`               // 字典ID
	ParentID     int64          `gorm:"column:parent_id;type:bigint;not null;comment:父级ID（0表示根节点）" json:"parent_id"`               // 父级ID（0表示根节点）
	Code         string         `gorm:"column:code;type:varchar(100);not null;comment:字典项编码" json:"code"`                          // 字典项编码
	Name         string         `gorm:"column:name;type:varchar(200);not null;comment:字典项名称" json:"name"`                          // 字典项名称
	Description  *string        `gorm:"column:description;type:text;comment:字典项描述" json:"description"`                             // 字典项描述
	IconURL      *string        `gorm:"column:icon_url;type:varchar(500);comment:图标URL" json:"icon_url"`                           // 图标URL
	SortOrder    int32          `gorm:"column:sort_order;type:int;not null;comment:排序序号（升序）" json:"sort_order"`                    // 排序序号（升序）
	Level        int32          `gorm:"column:level;type:int;not null;default:1;comment:层级（1开始）" json:"level"`                     // 层级（1开始）
	Path         string         `gorm:"column:path;type:varchar(1000);not null;comment:路径（如: 1/2/3）" json:"path"`                  // 路径（如: 1/2/3）
	Status       int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态：1-启用，0-禁用" json:"status"`          // 状态：1-启用，0-禁用
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                          // 软删除时间
}

// TableName OrbiaDictionaryItem's table name
func (*OrbiaDictionaryItem) TableName() string {
	return TableNameOrbiaDictionaryItem
}
