// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	admin "orbia_api/biz/router/admin"
	auth "orbia_api/biz/router/auth"
	common "orbia_api/biz/router/common"
	kol "orbia_api/biz/router/kol"
	order "orbia_api/biz/router/order"
	team "orbia_api/biz/router/team"
	upload "orbia_api/biz/router/upload"
	user "orbia_api/biz/router/user"
	wallet "orbia_api/biz/router/wallet"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	admin.Register(r)

	upload.Register(r)

	wallet.Register(r)

	order.Register(r)

	team.Register(r)

	auth.Register(r)

	common.Register(r)

	kol.Register(r)

	user.Register(r)

}
