// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	ad_order "orbia_api/biz/router/ad_order"
	admin "orbia_api/biz/router/admin"
	auth "orbia_api/biz/router/auth"
	common "orbia_api/biz/router/common"
	dictionary "orbia_api/biz/router/dictionary"
	kol "orbia_api/biz/router/kol"
	kol_order "orbia_api/biz/router/kol_order"
	payment_setting "orbia_api/biz/router/payment_setting"
	team "orbia_api/biz/router/team"
	upload "orbia_api/biz/router/upload"
	user "orbia_api/biz/router/user"
	wallet "orbia_api/biz/router/wallet"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment_setting.Register(r)

	dictionary.Register(r)

	ad_order.Register(r)

	kol_order.Register(r)

	admin.Register(r)

	upload.Register(r)

	wallet.Register(r)

	team.Register(r)

	auth.Register(r)

	common.Register(r)

	kol.Register(r)

	user.Register(r)

}
