// Code generated by hertz generator.

package team

import (
	"orbia_api/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _updateMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _listMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _inviteMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _acceptinvitationMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _rejectinvitationMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _membersMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _createteamMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getuserinvitationsMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _team_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getteamMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _inviteuserMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getteammembersMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _memberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removeteammemberMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _updateteamMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _getuserteamsMw() []app.HandlerFunc {
	// 需要JWT认证
	return []app.HandlerFunc{mw.AuthMiddleware()}
}

func _invitationMw() []app.HandlerFunc {
	// your code...
	return nil
}
